#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# 02_deploy.sh — Deploy contracts to local Anvil and write e2e/.env.local
#
# Requires: anvil running (01_start_anvil.sh), foundry installed, jq installed
# Output:   deployments/local.json  (repo root)
#           e2e/.env.local
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
E2E_DIR="$REPO_ROOT/e2e"
DEPLOYMENTS_DIR="$REPO_ROOT/deployments"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
for cmd in forge cast jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd not found." >&2
    exit 1
  fi
done

if ! cast block --rpc-url http://localhost:8545 &>/dev/null; then
  echo "ERROR: Anvil not reachable at http://localhost:8545. Run 01_start_anvil.sh first." >&2
  exit 1
fi

mkdir -p "$DEPLOYMENTS_DIR"

# ── Run forge script ──────────────────────────────────────────────────────────
echo "Deploying contracts..."
echo ""

cd "$REPO_ROOT/contracts"
forge script script/LocalSetup.s.sol \
  --tc LocalSetup \
  --rpc-url http://localhost:8545 \
  --broadcast

echo ""

# ── Parse output ──────────────────────────────────────────────────────────────
JSON="$DEPLOYMENTS_DIR/local.json"

if [[ ! -f "$JSON" ]]; then
  echo "ERROR: $JSON was not written. Check forge output above." >&2
  exit 1
fi

PROTOCOL=$(jq -r '.protocol'  "$JSON")
USDC=$(jq -r '.usdc'          "$JSON")
WBTC=$(jq -r '.wbtc'          "$JSON")
WETH=$(jq -r '.weth'          "$JSON")
BTC_ORACLE=$(jq -r '.btcOracle' "$JSON")
ETH_ORACLE=$(jq -r '.ethOracle' "$JSON")
START_BLOCK=$(jq -r '.startBlock' "$JSON")

# ── Write e2e/.env.local ──────────────────────────────────────────────────────
cat > "$E2E_DIR/.env.local" << EOF
# Generated by 02_deploy.sh — do not edit by hand
RPC_URL=http://localhost:8545
CONTRACT_ADDRESS=$PROTOCOL
START_BLOCK=$START_BLOCK
SOLVER_FEE_RATE=10

# Token addresses
USDC=$USDC
WBTC=$WBTC
WETH=$WETH
BTC_ORACLE=$BTC_ORACLE
ETH_ORACLE=$ETH_ORACLE

# Anvil accounts (index → role)
DEPLOYER=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
DEPLOYER_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
LENDER1=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
LENDER1_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
LENDER2=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
LENDER2_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
BORROWER=0x90F79bf6EB2c4f870365E785982E1f101E93b906
BORROWER_KEY=0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
SOLVER=0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
SOLVER_KEY=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926b
LIQUIDATOR=0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc
LIQUIDATOR_KEY=0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
EOF

echo "✓ Protocol:    $PROTOCOL"
echo "✓ USDC:        $USDC"
echo "✓ WBTC:        $WBTC"
echo "✓ WETH:        $WETH"
echo "✓ Start block: $START_BLOCK"
echo ""
echo "Written: deployments/local.json"
echo "Written: e2e/.env.local"
echo ""
echo "Next: run 03_start_backend.sh and 04_start_frontend.sh in separate terminals."
